# Используем готовый образ, где уже ЕСТЬ Chrome и Node.js
FROM ghcr.io/puppeteer/puppeteer:latest

USER root
WORKDIR /app

# Копируем настройки проекта
COPY package*.json ./
RUN npm install

# Копируем весь код
COPY . .

# Открываем порт (на Hugging Face это обычно 7860)
EXPOSE 7860
ENV PORT=7860

CMD ["node", "server.js"]